spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory
              uri: lb://INVENTORY
              predicates:
                - Path=/orders/**
              filters:
                - name: LoggingOrdersFilter
            - id: order
              uri: lb://ORDER
              predicates:
                - Path=/inventory/**
