spring:
  cloud:
    gateway:
      routes:
        - id: inventory
          uri: lb://INVENTORY
          predicates:
            - Path=/orders/**
          filters:
            - name: LoggingOrdersFilter

        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
